### PR TITLE
Port to Python 3

### LINKED ISSUE #2: Port to Python 3
Port the activity to Python 3 and the Sugar Toolkit for GTK+ 3.

Requires some of https://github.com/sugarlabs/sugar-toolkit-gtk3/issues/382 to be completed.

### PR DESCRIPTION
**Pull request by rhl-bthr**
Fixes #2

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.  I'm not surprised the change is so minimal, as Hello World has always been our exemplar.  Holding this pull request open for the moment until the project reaches the necessary stage; toolkit release.

**Review by rhl-bthr — COMMENTED** [review]
LGTM

**Comment by quozl** [comment]
Rebased against _master_.

**Comment by Aniket21mathur** [comment]
Tested with Sugar v 0.114. With both python2 (sugar-activity .) and python3 (sugar-activity3 .).

**Comment by quozl** [comment]
Tested.  Is incomplete because toolkit is incomplete.

**Comment by rhl-bthr** [comment]
@quozl @aniket21mathur, please review

**Comment by Aniket21mathur** [comment]
Reviewed and tested. Thanks!

**Pull request merged**
